apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "codimd.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "codimd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "codimd.labels" . | nindent 6 }}
  template:
    metadata:
      name: {{ template "codimd.fullname" . }}
      labels:
        app.kubernetes.io/component: server
        {{- include "codimd.labels" . | nindent 8 }}
      annotations:
        {{ toYaml .Values.codimd.podAnnotations | nindent 8 }}
    spec:
      affinity:
      {{ toYaml .Values.codimd.affinity | nindent 8 }}
      tolerations:
      {{ toYaml .Values.codimd.tolerations | nindent 8 }}
      nodeSelector:
      {{ toYaml .Values.codimd.nodeSelector | nindent 8 }}

      {{ if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{ .Values.image.pullSecrets | nindent 8 }}
      {{end }}
      containers:
        - name: codimd
          image: {{ template "codimd.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CMD_USE_CDN
              value: {{ .Values.codimd.security.useCDN | quote }}
            - name: CMD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "codimd.fullname" . }}-database-secret
                  key: connection
          envFrom:
            - secretRef:
                name: {{ template "codimd.fullname" . }}-auth-env
          ports:
            - name: http
              containerPort: 3000
      restartPolicy: Always
